"""empty message

Revision ID: 0b488c733a4d
Revises: 9c8df0482c9c
Create Date: 2017-09-25 18:19:52.618603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b488c733a4d'
down_revision = '9c8df0482c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arxiv_project', sa.Column('identifier', sa.String(), nullable=True))
    op.add_column('arxiv_project', sa.Column('submitted', sa.Date(), nullable=True))
    op.drop_column('arxiv_project', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arxiv_project', sa.Column('created', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('arxiv_project', 'submitted')
    op.drop_column('arxiv_project', 'identifier')
    # ### end Alembic commands ###
