"""empty message

Revision ID: 9c8df0482c9c
Revises: ccf0c11019b4
Create Date: 2017-09-25 17:17:32.042558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8df0482c9c'
down_revision = 'ccf0c11019b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arxiv_project', sa.Column('abstract', sa.String(), nullable=True))
    op.add_column('arxiv_project', sa.Column('authors', sa.String(), nullable=True))
    op.add_column('arxiv_project', sa.Column('categories', sa.String(), nullable=True))
    op.add_column('arxiv_project', sa.Column('created', sa.Date(), nullable=True))
    op.add_column('arxiv_project', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arxiv_project', 'title')
    op.drop_column('arxiv_project', 'created')
    op.drop_column('arxiv_project', 'categories')
    op.drop_column('arxiv_project', 'authors')
    op.drop_column('arxiv_project', 'abstract')
    # ### end Alembic commands ###
