"""empty message

Revision ID: f142843ee793
Revises: 0b488c733a4d
Create Date: 2017-09-25 18:28:06.188336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f142843ee793'
down_revision = '0b488c733a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'arxiv_project', ['identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arxiv_project', type_='unique')
    # ### end Alembic commands ###
